services:

  judge0-server:
    image: judge0/judge0:1.13.1
    ports:
      - "2358:2358"
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always
    depends_on:
      - judge0-db
      - judge0-redis

  judge0-workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always
    depends_on:
      - judge0-db
      - judge0-redis

  judge0-db:
    image: postgres:16
    environment:
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0pass
    volumes:
      - judge0_db:/var/lib/postgresql/data

  judge0-redis:
    image: redis:7
    command: redis-server --save "" --appendonly no
    volumes:
      - judge0_redis:/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no

volumes:
  judge0_db:
  judge0_redis: